### ISSUE TITLE
Determine the impact of blob size on Hadoop jobs

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#108]
As part of our _cold storage_ scenario, we are creating blobs that we expect to be processed by Hadoop at some point. Some implementations (such as our custom event processor) allow us some control over the size of the blobs. What are the considerations?

For background, here's a [post on merging small files](http://blogs.msdn.com/b/mostlytrue/archive/2014/04/10/merging-small-files-on-hdinsight.aspx).

Also, we ran some informal tests a few months ago with a 20GB dataset.
Broken into 1MB files, our query took ~400s.
Broken into 2GB files, our query took ~200s.

**Comment by lbrader** [comment]
In running the long running jobs - I had over 20GB in the blob storage and the hive job timed out at 1 hour.

**Comment by hveiras** [comment]
Our findings on this topic are in agreement whit this post http://blogs.msdn.com/b/mostlytrue/archive/2014/04/10/merging-small-files-on-hdinsight.aspx

Note that if you are using ColdSotrageProcessor you can choose the size of the blobs from the configuration file.
