### ISSUE TITLE
Split the Stream Analytics job into seperate jobs for each path

### ISSUE THREAD

**Issue by JohnPWSharp** [mspnp/iot-journey#114]
The SA job fabrikamstreamjob01 with two different outputs. Is this best practice? Would it be better to split the job in two and create separate jobs for each outputs?

**Comment by tomkerkhove** [comment]
Sounds like a good idea but I think it's a matter of price - Do you want to pay for the seperation/seperate scalability or just want one job to handle it?

My personal opinion would be to seperate them indeed.

**Comment by lbrader** [comment]
associated with #30.  Will do a spike on this item. Changed the size

**Comment by bennage** [comment]
I agree with @tomkerkhove's concern. We need to understand the cost difference. Likewise, is there a performance implication. You'll have two jobs both consuming egress from the Event Hub.

**Comment by tomkerkhove** [comment]
Exactly, I think it would be nice to have a look at both scenarios, talk about the pro's & con's and then implement one in this solution. Does this make sense?

**Comment by lbrader** [comment]
Last part of this task is to update the provisioning script to create a second SA job.

**Comment by lbrader** [comment]
On the subject of having 2 SA jobs.  One of the reason to separate them out is division of concerns.  1 SA job is for the warm path scenario where the other SA job is for the cold path scenario.   The issue surfaced when our SQL died and killed the warm path, but it also killed the cold storage scenario.
