### ISSUE TITLE
Update the personas for the fictious customer team

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#123]
Regarding the personas described in journal introduction:
- Beth should be concerned about the _operational cost_ of Fabrikam's solution.
- Poe's description feels outdated. We should modernize it to reflect popular thinking and terminology in the devops space.
- We need to add _Gary_ the security specialist.

**Comment by tomkerkhove** [comment]
Great to see that Gary joined Fabrikam, his vision is really important and appreciate your guidance on this!

**Comment by bennage** [comment]
:+1:
