### ISSUE TITLE
Azure storage problem on provisioning

### ISSUE THREAD

**Issue by ppatierno** [mspnp/iot-journey#125]
Hi,
I'm following the instructions on building the solution and setting up the Azure assets from this page : 

https://github.com/mspnp/iot-journey/blob/master/docs/building-and-deploying-the-sample-solution.md

It seems that the script works fine but I have a problem with Azure storage creation.
Documentation says that in the "container01refdata" container I should have "fabrikam" folder with "buildingdevice.json" file. However I haven't this file (and related folder) ... the container is empty.
I can't see any errors during the script execution.

Thanks,
Paolo.

**Comment by JohnPWSharp** [comment]
The step that creates this folder and uploads the file is currently missing from the provisioning script (it is being addressed). You can perform this step manually:

1. Copy the file fabrikam_buildingdevice.json in the provision folder to file buildingdevice.json, 
2. Create the fabrikam folder in the container01refdata container using any tool that gives you access to Azure storage (such as Server Explorer in Visual Studio)
3. Upload the buildingdevice.json file to the fabrikam folder

**Comment by ppatierno** [comment]
It's ok thanks. :-)

I think that the documentation needs another update : the first 11 ColdStorage tests related to Blob Writer fail (on my side) due to the need to update the "storageconnectionstring" in the App.config file.
It isn't written in the documentation.

Paolo.

**Comment by lbrader** [comment]
#92 pull request address this issue.  We have moved the all settings to mysettings.config and it's now created when running the provisioning scripts.  I'll check the readme to reflect these updates today.
