### ISSUE TITLE
Produce a video journal

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#143]
We're finding that there is a lot of information to process in this space.
We believe that having a a set of short videos exploring certain aspects of the project would be valuable.
It's too early to start producing these videos, however we want to start thinking about them.
What are topics that we should cover?
What's the right channel to use?

**Comment by tomkerkhove** [comment]
This makes sense as these videos can cover specific topics such as security. This enables you to only watch that video if this is part of your concern.

With channel do you mean where these should be available? I think on the P&P website would be find, maybe on Channel9 as a series as well?

Topics can be security, storage, data ingestion, etc.

**Comment by bennage** [comment]
We have kicked this off. https://channel9.msdn.com/blogs/mspnp
