### ISSUE TITLE
Structure the repo to support multiple implementations

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#147]
For each of our scenarios, we will have one or more implementations. For example, for the **cold storage** scenario we have:
- a custom event processor written in .NET
- a Stream Analytics job
- a Storm topology (Java)

There are all concrete implementations that solve the same problem. It is also possible that we will have even more implementations (e.g. NodeJS) for such a scenario.

How can we structure the repo to support this?

**Comment by hveiras** [comment]
I suggest something like

ColdStorage/EventProcessor
ColdStorage/ASA
ColdStorage/Strom

We should see what is the best option for code sharing between projects when applicable. IMO each scenario should be deployed separately if you want and resources be identified with scenario name or id in those cases we provide scripts to do provision. I think that will help to understand clearly which resource belongs to each scenario.

Other ideas?

**Comment by bennage** [comment]
I was thinking something similar. My concern was root level assets such the .sln and shared code assets.
I guess that we would need a root .sln in what we're describing.
Shared assets could be something like
Common/DotNet

**Comment by bennage** [comment]
I discussed this with @francischeung and we have a consensus. Let's go with what we've been disucssing.

**Comment by hanzzhang** [comment]
The final result is the PR #213
