### ISSUE TITLE
Update ScenarioSimulator logging

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#153]
Make sure that the event that shows the current number of messages sent is at a higher level of logging than the event of sending each message.

**Comment by bennage** [comment]
This is already the case.
Sending each event is [**Verbose** ](https://github.com/mspnp/iot-journey/blob/02aebd1fd9ad5eda7bdf6304bd3ad58bdb65d501/src/Implementation/Shared/Core/Logging/ScenarioSimulatorEventSource.cs#L142-L146).
The current count is [**Informational**](https://github.com/mspnp/iot-journey/blob/02aebd1fd9ad5eda7bdf6304bd3ad58bdb65d501/src/Implementation/Shared/Core/Logging/ScenarioSimulatorEventSource.cs#L154-L158).
