### ISSUE TITLE
Provision device: deny SAS token

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#158]
Find out if there is a way to deny a token request from a blacklisted publisher. We can revoke the publisher with the namespace manager but does that also deny the publisher new SAS tokens?

Is there a better way to deny publishers renewing their SAS token?

**Comment by mj1856** [comment]
See also #156

**Comment by francischeung** [comment]
I can see a number of things happening:
1) publisher is denied new token
2) publisher's event messages are blocked, even with a valid token
3) publisher is able to get an updated token.

I just want us to understand what really happens.
