### ISSUE TITLE
Investigate the performance characteristics of the simulator

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#161]
The simulator does not send the number of events that are expected.
For example, if we configure it for 2,000 devices to send 1 event/sec, the simulator only reports sending about 60% of that number. We would like to understand why.

**Comment by mj1856** [comment]
Some things to test:
- set `ConfigureAwait(false)`
- comment on the network calls
- limit to one messaging factory

**Comment by mj1856** [comment]
Add to the logs:
- time elapsed since last log message (for current count)
- difference in count since last log message

**Comment by lbrader** [comment]
Issues found to date.

Major 
- Adding the Async Message pump has reduced the # of threads but has caused an issue of all the async task running on the Main thread.

In our analysis of adding ConfigureAwait(false); to the various await calls we found out that in SimulationProfile.cs code SimulateDeviceAsync function is where we need to specifically add the ConfigureAwait(false) to the following await. 


            try
            {
                await Task.Delay(waitBeforeStarting, token).ConfigureAwait(false);
            }
            catch (TaskCanceledException)
            {
                return;
            }

We were a bit surprise that this statement corrected the issue of all threads running on the Main Thread, each now ran on a thread from the thread pool, which is the operation we want to see. 

The reason for this working is that it's 


Minor
- setting 0 to # devices or # of factories per device result in divide by zero

**Comment by lbrader** [comment]
#170, #171 will fix the issues found here.

**Comment by bennage** [comment]
I've created some new issues reflecting problems that we have identified:
- #175 
- #174
