### ISSUE TITLE
Fix Async Message Pump

### ISSUE THREAD

**Issue by lbrader** [mspnp/iot-journey#171]
We recently added a Message Pump #138 to our main to get more effective with our thread management. 

This caused an issue with marshaling all the threads on to the main thread, since we didn't have a .ConfigureAwait(false) on any of the await task.  

To fix this item we need to add on all await task a .ConfigureAwait(false) starting in Program.cs with the top await call shown below.  
     await deviceSimulator.RunSimulationAsync(scenario, ct);

should be 
     await deviceSimulator.RunSimulationAsync(scenario, ct).ConfigureAwait(false);

Note: There are 2 await calls in Program.cs.

Probably should be added after #156, #157  PR are done

**Comment by lbrader** [comment]
Related to #161.

**Comment by bennage** [comment]
Could we push some more of the message pump bits into the console host class? It looks like it's a bit redundant across the console hosts. It doesn't need to happen as part of this work item. I just want opinions. If there's a consensus. we'll add a specific work item.

**Comment by lbrader** [comment]
Must do this for the ColdStorage code.

**Comment by lbrader** [comment]
The goal for this task was to add ConfigureAwait(false) to the Solution where appropriate.   

 @bennage Taking a look at moving more of the message pump bits to the console host class is very doable - probably a couple of hours.  Created task #187 to consolidate the message pump code to console host.
