### ISSUE TITLE
Emit the "events per second" for the simulator.

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#176]
We currently emit the total current count for all devices: `ScenarioSimulatorEventSource.Log.CurrentEventCountForAllDevices`

In addition to this, I would like to emit the current events per second (during a specified window). For example, if we want to emit this value every 6 seconds:

``` C#
            var interval = TimeSpan.FromMinutes(0.1);
            _observableTotalCount
                .Buffer(interval)
                .Scan(0, (total, next) => next.Sum())
                .Subscribe(count =>
                Console.WriteLine("{0} per second", (count / interval.TotalSeconds))
                );
```

I don't want to output to console though. This should use EventSource like everything else. It could be combined into the existing `CurrentEventCountForAllDevices`

**Comment by bennage** [comment]
Please limit the significant digits. :-)

**Comment by lbrader** [comment]
I'll pick this up.  Working on closing the simulator task

**Comment by lbrader** [comment]
From our analysis of long running the system #30 we included this updated and found it had issues in accuracy. Updating the pull request with these fixes.
