### ISSUE TITLE
Consolidate Async Message Pump into Console Host

### ISSUE THREAD

**Issue by lbrader** [mspnp/iot-journey#187]
The goal is to reduce duplication of code with the Async Message Pump.  Suggestion from #171.

@bennage original request. 

Could we push some more of the message pump bits into the console host class? It looks like it's a bit redundant across the console hosts. It doesn't need to happen as part of this work item. I just want opinions. If there's a consensus. we'll add a specific work item.

**Comment by bennage** [comment]
The pump was removed as unnecessary. I'm closing this request.
