### ISSUE TITLE
Publish status update early July

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#210]
We've been having conference calls to communicate status and request feedback. We are due to update our status this week. Instead of a conference call, let's record a video.

**Comment by francischeung** [comment]
I think that we should produce videos on the following topics:
- [ ] Long Term Storage (Blob) using .NET EventProcessor, validated with Hive query
- [ ] Long Term Storage (Blob) using Azure Stream Analytics, validated with Hive query
- [ ] Warm Data Aggregation using Azure Stream Analytics and Azure SQL DB
- [ ] Warm Data Adhoc Exploration using .NET EventProcessor and Elasticsearch/Kibana
- [ ] Example Elasticsearch cluster in Azure

**Comment by bennage** [comment]
This looks good.

**Comment by francischeung** [comment]
I will do 1,2,4, and 5 easily. Someone else could record #3, as I'm less familiar with that codebase. Otherwise, it will be a forcing function for me to get familiar.

**Comment by bennage** [comment]
This sound reasonable.

**Comment by bennage** [comment]
Once the first videos are posted, we should like to https://channel9.msdn.com/Blogs/mspnp on the project readme.

**Comment by francischeung** [comment]
First Video: https://channel9.msdn.com/Blogs/mspnp/IoT-Journey-Long-Term-Storage-using-Azure-Stream-Analytics

**Comment by francischeung** [comment]
Second Video:  https://channel9.msdn.com/Blogs/mspnp/IoT-Journey-Long-Term-Storage-using-a-Custom-Event-Processor

**Comment by bennage** [comment]
:+1:

**Comment by francischeung** [comment]
Third Video: https://channel9.msdn.com/Blogs/mspnp/IoT-Journey-Warm-Data-Ad-Hoc-Exploration-with-Elasticsearch-and-Kibana

**Comment by francischeung** [comment]
Fourth Video: https://channel9.msdn.com/Blogs/mspnp/IoT-Journey-Example-Elasticsearch-Cluster-in-Azure

**Comment by francischeung** [comment]
@lbrader mentioned he was interested in recording:  "Warm Data Aggregation using Azure Stream Analytics and Azure SQL DB"

Assigning to Larry.

**Comment by bennage** [comment]
@lbrader please follow the format and approached established by Francis. Can you provide an ETA?

**Comment by lbrader** [comment]
@bennage, definitely interested.  I'll start working on this tomorrow, when i'm back in.

**Comment by francischeung** [comment]
Fifth Video: https://channel9.msdn.com/Blogs/mspnp/IoT-Journey-Warm-Data-Aggregation-using-Azure-Stream-Analytics-and-SQL-DB
