### ISSUE TITLE
Rename project file name to be consistent with the scenario

### ISSUE THREAD

**Issue by hanzzhang** [mspnp/iot-journey#218]
We should rename:
- WarmStorage to AdhocExploration
- ColdStorage to LongTermStorage
- ScenarioSimulator to Simulator

In addition,
- WarmStorage.EventProcessor.ConsoleHost.Template.config to settings.template.config (with the real file being settings.config)

- ColdStorage.EventProcessor.ConsoleHost.Template.config to settings.template.config (with the real file being settings.config).

- ScenarioSimulator.ConsoleHost.Template.config to settings.template.config (with the real file being settings.config).

**Comment by bennage** [comment]
I definitely agree with WarmStorage  and ColdStroage, but I am not sure about ScenarioSimulator. I thought that including "Scenario" in the name helps to clarify the intent. Thoughts?

**Comment by hanzzhang** [comment]
I discussed more with Christopher and we feel that it's OK to leave the project name be different from the parent scenario name. The reason is the each scenario may consist multiple projects in the future, so each project will have different names and they may not necessarily be the same as their parent scenario name. Actually, making them the same may cause confusion.

**Comment by bennage** [comment]
:+1:
