### ISSUE TITLE
Issues with Cold Storage Event Processor

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#237]
After "Provision Resources" has been executed, the "Run Cold Storage Consumer" takes several tries before successfully running

**Comment by bennage** [comment]
Are there error messages? or is it just timing out?

**Comment by francischeung** [comment]
Warning messages:

WARNING: The Switch-AzureMode cmdlet is deprecated and will be removed in a future release.

WARNING: The names of some imported commands from the module 'AzureARM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'AzureStorage' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the
Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'AzureServiceBus' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the
Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: GeoReplicationEnabled property will be deprecated in a future release of Azure PowerShell. The value will be merged into the AccountType property.

**Comment by bennage** [comment]
These are warnings from the PowerShell scripts, correct?

**Comment by francischeung** [comment]
Yes

**Comment by francischeung** [comment]
Perhaps this was transient. I haven't seen the original issue in a while.

**Comment by bennage** [comment]
We'll reopen the issue if we see it again.
