### ISSUE TITLE
Turn on approved FxCop rules

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#243]
Decide with the team which FxCop rules to turn on and then do so.

**Comment by francischeung** [comment]
Currently, the projects are using the "Microsoft Managed Recommended Rules"

**Comment by francischeung** [comment]
Tasks:
- [ ] Determine rule set to use across all projects
- [ ] Run code analysis on each solution
- [ ] Resolve issues found by code analysis
- [ ] Turn on code analysis on build

**Comment by francischeung** [comment]
The Quality Essentials tool suggest that we download the FxCop plugin and run the SDL 7 ruleset.

**Comment by francischeung** [comment]
The projects in the ScenarioSimulator solution have been updated to point to the custom IoTJourney.ruleset and to run code analysis on build.
This needs to be done on the other 3 solution's projects.

**Comment by bennage** [comment]
@hveiras can you please review the pr?
