### ISSUE TITLE
Add to Web Jobs unique device name per Web Job

### ISSUE THREAD

**Issue by lbrader** [mspnp/iot-journey#261]

**Comment by hveiras** [comment]
data-pipeline (WebRole)

- DeploymentId -> RoleEnvironment.DeploymentId -> Not Used
- SourceName -> RoleEnvironment.CurrentRoleInstance.Id -> used as 'hostName' in SimulatorProfile
- RoleName -> RoleEnvironment.CurrentRoleInstance.Role.Name -> Used in Nlog - InstanceIndex -> Not Used
- InstanceName -> RoleEnvironment.CurrentRoleInstance.Id -> Used in SimulatorProfile and NLog

iot-journey (WebJob)

- SourceName -> Currently hardoded to "Console" -> Consider using WEBJOBS_NAME Environment variable

**Comment by hveiras** [comment]
List of available Env variables for WebJobs
