### ISSUE TITLE
Consider updating setup scripts: increasing the scale unit value for Stream Analytics jobs

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#262]

**Comment by bennage** [comment]
We want a setting that will allow for a theoretical limit of 20,000 events per sec.

**Comment by hveiras** [comment]
Does it make sense to postpone this a bit and do it with ARM?

**Comment by bennage** [comment]
Yes. In fact, the ARM template that I've been experimenting with already includes this.

**Comment by bennage** [comment]
We can cover this in #312.
