### ISSUE TITLE
Update to Microsoft Azure Service Bus 3.0.x

### ISSUE THREAD

**Issue by hveiras** [mspnp/iot-journey#296]
There are a lot of improvements we can benefit on in this new version:

https://www.nuget.org/packages/WindowsAzure.ServiceBus

**Comment by hveiras** [comment]
It is better to merge #305 before continuing with this one

**Comment by bennage** [comment]
Feel to update any other packages. We should also use this opportunity to esnure
- [ ] package versions are consistent across all projects
- [ ] packages are stored in a common location for all projects
