### ISSUE TITLE
Scale up volume and duration events

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#30]
Update `ScenarioSimulator` to produce 100k events per min. That is **100,000** devices producing **1 event** each **per minute**.

Once we achieve that level of throughput, we should then run simulator continuosly for at least  **7 days**. We'll explicitly check for issues/bugs at checkpoints:
 1. 1 day
 1. 2 days
 1. 7 days 

We are especially interested in validating that we are investing and processing events, not so much that events are being sent.
If we find issues/bugs we will add new items to the backlog.

We want to investigate the stability of our prototype solution.

**Comment by bennage** [comment]
We need to finish #47 first.

**Comment by lbrader** [comment]
Setting this up a new VM for doing the 7 day test

**Comment by bennage** [comment]
I'd like to do a sanity check on this once a day. Let's calculate how many events were are expecting to be sent and compare that to the simulator's output.

**Comment by lbrader** [comment]
Compare the following:
- how many events we expect
- how many events we sent
- how many events did the hive query read

**Comment by lbrader** [comment]
Reset the entire test to work with the latest code with fixes from #113 #

**Comment by bennage** [comment]
Adding some details around:
- how many events we expect
- how many events we sent
- how many events did the hive query read

### how many events we expect
Just the math: `events/sec` * `number of seconds ran`
This is our hypothetical number.

### how many events we sent
This is the number reported by the simulator. It emits this number every 5 minutes or so.

### how many events did the ~~hive~~ query read
This is the result of running a query. We'll run a query for each implementation that proceses __all__ events. In the "cold storage" scenario, this is a hive querty. However, in our "ad hoc exploration" scenario it will be in Elasticsearch.

**Comment by lbrader** [comment]
Will be launching another long run test starting late today.

**Comment by bennage** [comment]
For our initial expected load (2,000 events/sec), we expect the following:

- 7.2M events / hour
- 172.8M events/day

**Comment by bennage** [comment]
I've been running the simulator as a webjob. I configured it for 2,000 devices at 1 event/sec.
I'm only seeing **~1,167** events/secs coming out of the simulator. That's roughly 60%.

**Comment by francischeung** [comment]
I wonder if the jitter is causing a big delay.


-Francis



On Mon, Jun 22, 2015 at 3:57 PM -0700, "Christopher Bennage" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been running the simulator as a webjob. I configured it for 2,000 devices at 1 event/sec.
I'm only seeing ~1,167 events/secs coming out of the simulator. That's roughly 60%.

-

**Comment by bennage** [comment]
@lbrader asked the same question. It's possible, but I suspect it's something else. However, I don't have any data to go on yet.

**Comment by lbrader** [comment]
Update to this thread since our testing has resulted in a # of code fixes.
- Simulator Warm up
- Fix Jitter - was only adding a Positive value 
- Fix timing alignment for

**Comment by lbrader** [comment]
With code fixes & updates.   Setting up to do the following validation

Run the following Scenarios with the Web Job Simulator 
- 2000 devices with a single Simulator instance
- 20,000 devices with multiple Simulator instance
- 200,000 devices with multiple Simulator instance

Validate the following IOT
- Expected # of devices
- Expected throughput

Cold Storage
- Event Processor
- ASA 

Warm 
- Event Processor to Elastic Search

**Comment by bennage** [comment]
@lbrader can you schedule some time with @hveiras to go over the data and learnings you've collected so far?

**Comment by lbrader** [comment]
Test
- Deployed as a Web Job
- Validate
   - 1 Through Put Unit   be about 2000 devices 1 per second
  - 2 TU
  - 4 TU or Max TU to get 200,0000 devices

1 hour
48 hours

7 Days - once the above

**Comment by bennage** [comment]
I'm confused by this.
1. Why are we talking about validating TUs? That is not part of the task. Set it high enough to cover the expected load.
1. We're repeating info that was stated above (in some cases more than once).
1. The focus on _Server Busy_ is misplaced. If we are hitting the expected numbers, I don't care about the server busy exceptions. The SDK has a retry policy built in.

**Comment by bennage** [comment]
This has become too confused. We'll open a new issue that's clearly defined.
