### ISSUE TITLE
Make namespaces consistent in .NET code

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#305]
All of the .NET code should be in the namespace `Microsoft.Practices.IoTJourney`.
Use this as the basis for the default namespace for each assembly, as well as the basis for the assembly name.

**Comment by hveiras** [comment]
Can we make exception for console apps names? Having shorter names makes it easier when you want to call them by command line.

**Comment by bennage** [comment]
Yes.
________________________________
