### ISSUE TITLE
Introduction to IoT security

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#38]
An IoT systems presents lots of new security challenges. In addition, these challenges can have surprisingly drastic consequences.
We need to create a document describing the types of problems that need to be considered.

**Comment by bennage** [comment]
Pausing work on this until further notice.

**Comment by bennage** [comment]
@JohnPWSharp Did you see the email from me with the additional materials?

**Comment by JohnPWSharp** [comment]
I did, but I have not had time to digest them yet. I will resume work on this once I have got the provisioning, architecture, and overview docs out of the way.

**Comment by bennage** [comment]
Understood. Thanks.
________________________________

**Comment by JohnPWSharp** [comment]
This is effectively obsolete. A new doc is being created with a different structure and focus - see PR #163

**Comment by bennage** [comment]
I'm guessing that you mean that the work in #44 is obsolete. This item is still relevant for tracking the work in #163, correct?

**Comment by JohnPWSharp** [comment]
Yup

**Comment by JohnPWSharp** [comment]
I have taken this as far as I can initially based on the docs etc provided. It needs a thorough review.

**Comment by bennage** [comment]
Ack. Thanks.

**Comment by bennage** [comment]
Since @JohnPWSharp  is working on some other p&p projects, I've asked @MikeWasson to continue work on this. He's currently reviewing some source materials.
