### ISSUE TITLE
First journal entry

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#51]
We want to create a journal entry for the first milestone. The entry needs to include:
- the goals for the first milestone
- justifications for the choices we made
- our learnings and insights from the milestone

**Comment by bennage** [comment]
a draft is already in place:
https://github.com/mspnp/iot-journey/blob/master/docs/journal/01-first-steps.md

**Comment by bennage** [comment]
I just had a discussion with @JohnPWSharp. We decided to align the journal entries with the scenarios. We were doing this to some extent, but it will make the content more structured if we do so explicity. See #117.

The first journal entry should center around the _Cold Storage_ scenario.

**Comment by JohnPWSharp** [comment]
See doc 01-cold-storage.md in docs\journal folder (See #120)

**Comment by bennage** [comment]
@MikeWasson and I are doing some planning around the content. We'll be updating the issues in a couple of days to reflect the change.

**Comment by bennage** [comment]
I'm closing this issue due to the decisions made in #184 .
