### ISSUE TITLE
Research migrating provisioing script to ARM

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#52]
How much of our scripts can be migrated to ARM?
What is the effort level involved in migration?

**Comment by hveiras** [comment]
The majority of the components we are using are not supported/documented by ARM template at the moment (http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json). These are:

- EventHub
- HDInsight
- StreamAnalytics

I think the best for us is come back to this issue when those resources are available.

**Comment by bennage** [comment]
Agreed.
