### ISSUE TITLE
Explore alternative approach for warm storage: table storage

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#60]
In #47, we decided to target SQL as the output.
Let's see what is involved in sending the output to table storage.
The goal is to understand the trade-offs between the choices.
timebox: 5 hours

**Comment by lbrader** [comment]
This can be done adding a  new output directed to a table  in Streaming Analytic's.  Assigned the Partion  Key to the BuildingId and Row Key to the LastObservedTime.  I did have to up the # of devices to 200 to validate multiple buildings id. 


The trade-off comes down to consuming of the data.   There's a bit more provisioning for the SQL, but you get the Trigger.  Which you don't get with the Table.  Still the table is simple and is no-sql for other big data analysis. 

So adding tables is very straight forward.   We need a scenario for usage.
