### ISSUE TITLE
remove default parameters from provisioning script

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#65]
There are several parameters that should **not** have default values:
- subscription name
- service namespace
- storage account

**Comment by hveiras** [comment]
What about these ones?

    [String]$StreamAnalyticsJobName = "fabrikamstreamjob01",             

    [String]$ResourceGroupPrefix = "Fabrikam",
   
    [String]$EventHubName = "eventhub01",                   
    
    [String]$ServiceBusRuleName = "ManagePolicy",      

    [String]$ConsumerGroupName= "consumergroup01", 

    [String]$EventHubSharedAccessPolicyName = "ManagePolicy",
             
    [String]$StorageContainerName = "container01",

**Comment by bennage** [comment]
These are okay to have default values. They don't need to be globally unique.
________________________________

**Comment by lbrader** [comment]
working. closed with #67 pull request
