### ISSUE TITLE
Remove extra Scenarios from ScenarioSimulator

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#69]

**Comment by lbrader** [comment]
Scenario's to be removed
* EventsWithNoHandler 
* MalformedEvents
* LongRunningEvents

**Comment by francischeung** [comment]
These scenarios are defined in  src/Implementation/Simulator/ScenarioSimulator/SimulationScenarios.cs

**Comment by francischeung** [comment]
Connected to #75
