### ISSUE TITLE
Review the "timestamp" property for `UpdateTemperatureEvent`

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#72]
This involve:
- choosing a more descriptive name
- reviewing the usage

**Comment by hanzzhang** [comment]
changed property name TimeStamp to TimeObserved and changed the type from long to DateTime using DateTime.UtcNow

**Comment by bennage** [comment]
@hanzzhang What pull request closed this? We need to associate the code with the work item.

**Comment by hanzzhang** [comment]
connects to #63
