### ISSUE TITLE
Outstanding issues for the Build and Run document

### ISSUE THREAD

**Issue by JohnPWSharp** [mspnp/iot-journey#76]
Two things before this doc can be completed:

1. What is the data that is actually written to the JSON files in Blob storage for the two remaining scenarios? It would be useful to have this documented.

2. The Hive query is not generating output.

**Comment by lbrader** [comment]
For question 1. 

The only difference in the scenario's is that NoErrorsExpected gives a random temperature around 10 degree's Celsius.    Where the scenario ThrirtyDegreeReadings sets the temperature to 30 degree's Celsius.  The data format is identical for both scenario's.

The file UpdateTempatureEvent.cs in project Devices.Event contains the C# schema.  

The JSON in the blob is written out as follows :
{"timeobserved":"2015-06-02T21:28:03.1664095Z","DeviceId":"NOTCLOUD-77","Temperature":6.0,"EventProcessedUtcTime":"2015-06-02T21:28:40.6112882Z","PartitionId":11,"EventEnqueuedUtcTime":"2015-06-02T21:28:02.5240000Z"}

For question 2.

Adding the missing directory location fixed that issue on getting output.

**Comment by JohnPWSharp** [comment]
This information has been wound into the doc - see 37
