### ISSUE TITLE
Capture events for warm exploration

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#86]
This differs from #47.
We want to capture the entire event stream. We want to store the events someplace supports ad-hoc queries.

We expect to do this using an Event Processor (.NET) pumping events into some ElasticSearch instance.

**Comment by hveiras** [comment]
There are different options here. The current version of ES (1.5) does not support "Moving Average" queries which I understand they run indefinitely once you start them and keep the value updated for the set window. See: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-movavg-aggregation.html. This functionality is in ES master branch but is not yet officially released.

On the other hand if we only need an ad-hoc query to calculate the average that is already supported in 1.5. Alternatively we can define a query that automatically updates the time window each time it is called as done here: https://gist.github.com/clintongormley/9515005

**Comment by bennage** [comment]
We only need ad-hoc queries for the currently defined scenario.
