### ISSUE TITLE
Configure ElasticSearch on Azure

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#87]
We want to setup ElasticSearch on Azure. 
- How can we automatically remove old data? 
- How do we configure a cluster?
- What are reasonable defaults?

The is the storage described in #86.

**Comment by hveiras** [comment]
These scripts can be useful for point (2) https://github.com/mspnp/semantic-logging/tree/v3/ELK

**Comment by francischeung** [comment]
Configured a cluster of 3 nodes (VMs) running Elasticsearch. Each node is capable of becoming the master. The first VM is also running Kibana. The 3 ES nodes are in the same VNet as a 4th VM that is running the custom event processor. The custom event processor takes the events from EH and sends them to the internal load balancer that spreads load across the 3 ES nodes.
