### ISSUE TITLE
Explore using DocDb for warm exploration storage

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#88]
We are going to start off using ElasticSearch, but we think that DocDb might be a good fit for this scenario. 
We need to do some research and experimentation. and document our findinings.

**Comment by francischeung** [comment]
Azure DocumentDB limits and quotas:
https://azure.microsoft.com/en-us/documentation/articles/documentdb-limits/

Maximum Request Units / second per collection: 2500

**Comment by francischeung** [comment]
In order to scale up, it looks like you would need to partition the full data stream into multiple collections. This would complicate queries which would then need to run across collections.

**Comment by bennage** [comment]
We shoud verify what **Maximum Request Units ** really means.

**Comment by bennage** [comment]
Also, can this limit be overcome through batching?
