### ISSUE TITLE
Explore PowerBI for warm exploration

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#89]
Can we use PowerBI for storing the entire event stream and enabling ad-hoc querying of recent/warm events?
We're interested the capacity and throughput limits.
This relates to #86.

**Comment by francischeung** [comment]
PowerBI REST API:
https://msdn.microsoft.com/en-US/library/dn889825.aspx

*  Max rows per single push 10,000
* Single push is non-continuous. It does not mean that the table is empty to start and it does not need to complete in under a second
* Continuous push: Once per second at a max size of 500 rows with a max table size of 2 million rows
* 5 million row max per table
* Max of 5 pending request at one time

**Comment by francischeung** [comment]
Based on the above limitations, PowerBI is not a good fit for our "Warm Exploration" scenario where we send our full stream of raw data. The 5 million row max per table limit suggests that we can only send it filtered aggregated data.
