### ISSUE TITLE
Explore SQL for warm exploration

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#90]
Can we use SQL for storing the entire event stream and enabling ad-hoc querying of recent/warm events?
We're interested in throughput limits.
This relates to #86.

**Comment by francischeung** [comment]
Azure SQL DB perf limits:
https://msdn.microsoft.com/en-us/library/azure/dn741336.aspx

The highest service tier is Premium/P3:
1000 DTU, 500 GB max DB size, 735 transactions per second.

**Comment by francischeung** [comment]
Based on the perf limits above, it doesn't look like Azure SQL DB is a good fit for our "Warm Exploration" scenario where we need to persist our full stream of raw data (2k events per second, minimum).
