### ISSUE TITLE
Rationalize app config settings in the sample app

### ISSUE THREAD

**Issue by JohnPWSharp** [mspnp/iot-journey#92]
Most of the Azure configuration for the sample app is held in mysettings.config, but in the ColdStorage.ConsoleHost and ColdStorage.Tests projects that are additional Service Bus and Storage Account keys that you need to add to the app.config file.

Is it possible to put all of the Azure config stuff into the mysettings.config file?

Also, the unit test config files are separate from the configuration used by the ScenarioSimulator and ColdStorage console host projects. Is this good practice? Shouldn't unit tests use the same config as the apps themselves?

**Comment by bennage** [comment]
In our planning meeting, we decided that having a single config (mysettings.config) is better. However, we'd still like to keep the automated integration tests settings as separate keys in that file.

**Comment by hveiras** [comment]
@bennage I'm a bit confused about the last comment. Do we want to create new entries in the mysettings file for tests?

something like adding ColdStorage.Tests.StorageConnectionString?

**Comment by bennage** [comment]
That's correct. The motivation is to have one place to go to for all configuration settings. We still want unique keys for the tests.
