### ISSUE TITLE
Update the Warm Aggregation trigger for SQL

### ISSUE THREAD

**Issue by francischeung** [mspnp/iot-journey#96]
In the SQL table, that we write to for the Stream Analytics output (warm aggregation) we need to update the behavior of the trigger.

It appears tha Stream Analytics does a bulk insert into the table. We cannot guarantee the ordering of the inserts.

The desired behavior is:
- we don't want duplicate entries
- we want to make sure that we are writing the latest

**Comment by lbrader** [comment]
This issue is related to #67.  The SQL is killing Streaming Analytic's job
